# Scouting for All Pro/Pro-bowl Wide Recievers
**This project objective to use NFL combine statiscs data to explore any common stats that makes up a Pro-bowll/All-Pro WR. 
** We will use statisical analysis to see if there is any commonality within the Combine stats, to predict the future succuess of an NFL Wide Recievers

In [1]:
# Import needed dependencies 
import matplotlib.pyplot as plt 
import pandas as pd 
import scipy.stats as st 
import numpy as np 
from pprint import pprint 

#Set CSV Locations for each NFL Data Set in variable
combine_2000 = "Resources/combine_data.csv"
nfl_stats = "Resources/nfl_stats/Basic_Stats.csv"

# Use pandas csv reader to review data
combine_2000 = pd.read_csv(combine_2000)
nfl_stats = pd.read_csv(nfl_stats)

In [2]:
combine_2000.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6218 entries, 0 to 6217
Data columns (total 16 columns):
Player       6218 non-null object
Pos          6218 non-null object
Ht           6218 non-null int64
Wt           6218 non-null int64
Forty        6046 non-null float64
Vertical     4796 non-null float64
BenchReps    4212 non-null float64
BroadJump    4754 non-null float64
Cone         3993 non-null float64
Shuttle      4063 non-null float64
Year         6218 non-null int64
Pfr_ID       4895 non-null object
AV           6218 non-null float64
Team         3738 non-null object
Round        3738 non-null float64
Pick         3738 non-null float64
dtypes: float64(9), int64(3), object(4)
memory usage: 777.3+ KB

In [3]:
#view first 10 lines of combine_2000 data. Analyze data set to set goals for clean up
combine_2000.head(20)

,Player,Pos,Ht,Wt,Forty,Vertical,BenchReps,BroadJump,Cone,Shuttle,Year,Pfr_ID,AV,Team,Round,Pick
0,John Abraham,OLB,76,252,4.55,NaN,NaN,NaN,NaN,NaN,2000,AbraJo00,26.0,New York Jets,1.0,13.0
1,Shaun Alexander,RB,72,218,4.58,NaN,NaN,NaN,NaN,NaN,2000,AlexSh00,26.0,Seattle Seahawks,1.0,19.0
2,Darnell Alford,OT,76,334,5.56,25.0,23.0,94.0,8.48,4.98,2000,AlfoDa20,0.0,Kansas City Chiefs,6.0,188.0
3,Kyle Allamon,TE,74,253,4.97,29.0,NaN,104.0,7.29,4.49,2000,NaN,0.0,NaN,NaN,NaN
4,Rashard Anderson,CB,74,206,4.55,34.0,NaN,123.0,7.18,4.15,2000,AndeRa21,6.0,Carolina Panthers,1.0,23.0
5,Jake Arians,K,70,202,NaN,NaN,NaN,NaN,NaN,NaN,2000,arianjak01,0.0,NaN,NaN,NaN
6,LaVar Arrington,OLB,75,250,4.53,NaN,NaN,NaN,NaN,NaN,2000,ArriLa00,31.0,Washington Redskins,1.0,2.0
7,Corey Atkins,OLB,72,237,4.72,31.0,21.0,112.0,7.96,4.39,2000,AtkiCo20,1.0,NaN,NaN,NaN
8,Kyle Atteberry,K,72,167,NaN,NaN,NaN,NaN,NaN,NaN,2000,NaN,0.0,NaN,NaN,NaN
9,Reggie Austin,CB,69,175,4.44,35.0,17.0,119.0,7.03,4.14,2000,AustRe20,3.0,Chicago Bears,4.0,125.0
10,John Baker,P,75,227,NaN,NaN,NaN,NaN,NaN,NaN,2000,BakeJo21,4.0,NaN,NaN,NaN
11,Mark Baniewicz,OT,78,312,5.34,28.0,20.0,96.0,7.72,4.73,2000,NaN,0.0,NaN,NaN,NaN
12,Rashidi Barnes,FS,72,208,4.62,35.0,10.0,114.0,6.92,4.32,2000,BarnRa20,1.0,Cleveland Browns,7.0,225.0
13,David Barrett,CB,70,199,4.44,37.5,16.0,116.0,6.81,4.04,2000,BarrDa22,10.0,Arizona Cardinals,4.0,102.0
14,William Bartee,CB,73,192,4.43,38.5,NaN,124.0,6.70,3.99,2000,BartWi20,9.0,Kansas City Chiefs,2.0,54.0
15,Andrew Bayes,P,74,200,NaN,NaN,NaN,NaN,NaN,NaN,2000,NaN,0.0,NaN,NaN,NaN
16,Terrance Beadles,OG,75,312,5.19,NaN,29.0,NaN,NaN,NaN,2000,NaN,0.0,NaN,NaN,NaN
17,Robert Bean,CB,71,178,4.50,34.5,NaN,122.0,6.87,4.20,2000,BeanRo20,5.0,Cincinnati Bengals,5.0,133.0
18,Anthony Becht,TE,78,270,4.78,33.5,NaN,123.0,6.94,4.08,2000,BechAn00,7.0,New York Jets,1.0,27.0
19,Matt Beck,ILB,75,234,4.65,NaN,NaN,NaN,NaN,NaN,2000,NaN,0.0,NaN,NaN,NaN

In [4]:
#view first 10 lines of nfl_stats data. Analyze data set to set goals for clean up
nfl_stats.head(20)

,Age,Birth Place,Birthday,College,Current Status,Current Team,Experience,Height (inches),High School,High School Location,Name,Number,Player Id,Position,Weight (lbs),Years Played
0,NaN,"Grand Rapids , MI",5/23/1921,Notre Dame,Retired,NaN,3 Seasons,71.0,NaN,NaN,"Evans, Fred",NaN,fredevans/2513736,NaN,185.0,1946 - 1948
1,NaN,"Dayton , OH",12/21/1930,Dayton,Retired,NaN,1 Season,70.0,NaN,NaN,"Raiff, Jim",NaN,jimraiff/2523700,NaN,235.0,1954 - 1954
2,56.0,"Temple , TX",9/11/1960,Louisiana Tech,Retired,NaN,1 Season,74.0,NaN,NaN,"Fowler, Bobby",NaN,bobbyfowler/2514295,NaN,230.0,1985 - 1985
3,30.0,"New Orleans , LA",9/30/1986,LSU,Retired,NaN,5 Seasons,73.0,NaN,NaN,"Johnson, Quinn",NaN,quinnjohnson/79593,NaN,255.0,2009 - 2013
4,25.0,"Detroit , MI",3/31/1992,Central Michigan,Active,Pittsburgh Steelers,3rd season,77.0,Clintondale HS,"Clinton Twp.,Macomb Co., MI","Walton, L.T.",96.0,l.t.walton/2552444,DE,305.0,NaN
5,NaN,"Sumner , IL",9/11/1892,Illinois,Retired,NaN,1 Season,73.0,NaN,NaN,"Petty, Ross",NaN,rosspetty/2523136,NaN,180.0,1920 - 1920
6,NaN,"Casper , WY",9/16/1920,Wisconsin,Retired,NaN,3 Seasons,73.0,NaN,NaN,"Farris, Tom",NaN,tomfarris/2513861,NaN,185.0,1946 - 1948
7,22.0,"Navarre , FL",1/31/1995,Clemson,Active,New York Jets,Rookie,77.0,Navarre HS,FL,"Leggett, Jordan",NaN,jordanleggett/2557885,TE,250.0,NaN
8,NaN,NaN,NaN,No College,Retired,NaN,1 Season,NaN,NaN,NaN,"Thompson, Pinky",NaN,pinkythompson/2527303,NaN,NaN,1927 - 1927
9,98.0,"Alverton , PA",2/23/1919,Duquesne,Retired,NaN,1 Season,70.0,NaN,NaN,"Gonda, George",NaN,georgegonda/2515030,NaN,175.0,1942 - 1942
10,NaN,"Orlando , FL",3/8/1945,Tennessee Tech,Retired,NaN,3 Seasons,76.0,NaN,NaN,"Tanner, John",NaN,johntanner/2527011,NaN,231.0,1971 - 1974
11,56.0,"Alton , IL",2/10/1961,Southern University,Retired,NaN,1 Season,69.0,NaN,NaN,"Raglin, Floyd",NaN,floydraglin/2523695,NaN,180.0,1987 - 1987
12,33.0,NaN,12/4/1983,Boise State,Retired,NaN,1 Season,74.0,NaN,NaN,"Zabransky, Jared",NaN,jaredzabransky/2495791,NaN,219.0,2007 - 2007
13,27.0,"Little Rock , AR",11/22/1989,Arkansas,Retired,NaN,3 Seasons,71.0,NaN,NaN,"Adams, Joe",NaN,joeadams/2532782,NaN,185.0,2012 - 2014
14,73.0,"St. Louis , MO",12/8/1943,Missouri,Retired,NaN,8 Seasons,73.0,NaN,NaN,"Otto, Gus",NaN,gusotto/2522592,NaN,220.0,1965 - 1972
15,74.0,"Barberton , OH",9/1/1942,Florida A&M,Retired,NaN,3 Seasons,73.0,NaN,NaN,"Thomas, Gene",NaN,genethomas/2527241,NaN,210.0,1966 - 1968
16,66.0,"Indianola , IA",12/1/1950,Arizona,Retired,NaN,2 Seasons,74.0,NaN,NaN,"Demory, Bill",NaN,billdemory/2512778,NaN,195.0,1973 - 1974
17,25.0,NaN,3/11/1992,Pittsburgh,Active,Washington Redskins,1st season,74.0,NaN,NaN,"Garner, Manasseh",NaN,manassehgarner/2553801,TE,220.0,NaN
18,53.0,"New Orleans , LA",6/14/1963,Louisiana-Lafayette,Retired,NaN,9 Seasons,68.0,NaN,NaN,"Verdin, Clarence",NaN,clarenceverdin/2503464,NaN,160.0,1986 - 1994
19,50.0,"Scranton , PA",1/15/1967,Syracuse,Retired,NaN,1 Season,74.0,NaN,NaN,"DeRiggi, Fred",NaN,fredderiggi/2512828,NaN,268.0,1990 - 1990

* Sorting the Combine stats to focus on particular columns to what makes a pro-bowl Wide Reciever:
    In the sorted column we'll focus on :
    1. height of player
    2. Weight of player
    3. Run Forty time
    4. Vertical Jump
    5. Year they were drafted

In [7]:
sorted_wr_col = combine_2000[["Player","Pos","Ht","Wt","Forty","Vertical","Year"]]
print(sorted_wr_col.head(17))

              Player  Pos  Ht   Wt  Forty  Vertical  Year
0       John Abraham  OLB  76  252   4.55       NaN  2000
1    Shaun Alexander   RB  72  218   4.58       NaN  2000
2     Darnell Alford   OT  76  334   5.56      25.0  2000
3       Kyle Allamon   TE  74  253   4.97      29.0  2000
4   Rashard Anderson   CB  74  206   4.55      34.0  2000
5        Jake Arians    K  70  202    NaN       NaN  2000
6    LaVar Arrington  OLB  75  250   4.53       NaN  2000
7       Corey Atkins  OLB  72  237   4.72      31.0  2000
8     Kyle Atteberry    K  72  167    NaN       NaN  2000
9      Reggie Austin   CB  69  175   4.44      35.0  2000
10        John Baker    P  75  227    NaN       NaN  2000
11    Mark Baniewicz   OT  78  312   5.34      28.0  2000
12    Rashidi Barnes   FS  72  208   4.62      35.0  2000
13     David Barrett   CB  70  199   4.44      37.5  2000
14    William Bartee   CB  73  192   4.43      38.5  2000
15      Andrew Bayes    P  74  200    NaN       NaN  2000
16  Terrance Beadles   OG  75  312   5.19       NaN  2000

Pulling all WR comps that is needed

In [8]:
WR = sorted_wr_col["Pos"] == "WR"
print(sorted_wr_col[WR])

                        Player Pos  Ht   Wt  Forty  Vertical  Year
39             Plaxico Burress  WR  77  231   4.59      33.0  2000
46                 Kwame Cavil  WR  74  208   4.54      39.5  2000
58                  Chris Cole  WR  72  191   4.37      37.5  2000
60               Chris Coleman  WR  72  211   4.61      32.5  2000
61            Laveranues Coles  WR  71  192   4.41      34.0  2000
70               Chris Daniels  WR  75  217   4.74      33.0  2000
71             Brandon Daniels  WR  70  211   4.54       NaN  2000
75               JaJuan Dawson  WR  73  199   4.55      34.0  2000
81                  Ron Dugans  WR  73  206   4.58       NaN  2000
88                 Matt Farmer  WR  72  190   4.51      33.0  2000
89                Danny Farmer  WR  75  217   4.58       NaN  2000
91               Chafie Fields  WR  73  196   4.43       NaN  2000
95                Larry Foster  WR  70  198   4.55      37.0  2000
105              Trevor Gaylor  WR  75  199   4.56      37.5  2000
107             Sherrod Gideon  WR  71  173   4.66       NaN  2000
121                 Ricky Hall  WR  74  206   4.52       NaN  2000
126              Joey Hamilton  WR  73  201   4.54      36.0  2000
132             Windrell Hayes  WR  71  204   4.50       NaN  2000
135                Leroy Hodge  WR  73  215   4.54      34.5  2000
143              Trevor Insley  WR  72  192   4.70       NaN  2000
149            Darrell Jackson  WR  72  197   4.56       NaN  2000
164               Dwaune Jones  WR  72  191   4.66       NaN  2000
179              Marcus Knight  WR  73  180   4.72      28.5  2000
184                Charles Lee  WR  73  202   4.56      35.5  2000
187              Anthony Lucas  WR  75  194   4.53      35.0  2000
189                 Alton Lusk  WR  74  182   4.61      36.5  2000
205         Wendell Montgomery  WR  75  203   4.81      35.5  2000
206         Scottie Montgomery  WR  72  196   4.57      36.0  2000
207               Muneer Moore  WR  73  201   4.52      37.5  2000
211           Sylvester Morris  WR  75  216   4.60      34.5  2000
...                        ...  ..  ..  ...    ...       ...   ...
5999          Daesean Hamilton  WR  73  203    NaN      34.5  2018
6009         Quadree Henderson  WR  68  192   4.50      32.5  2018
6024      Darren Carrington II  WR  74  199    NaN      36.0  2018
6036              Richie James  WR  70  183   4.48      35.5  2018
6055            Christian Kirk  WR  70  201   4.47      35.5  2018
6057                Chris Lacy  WR  75  205   4.51      33.5  2018
6059             Jordan Lasley  WR  73  203   4.50      34.5  2018
6061              Allen Lazard  WR  77  227   4.55      38.0  2018
6072            Tavares Martin  WR  73  177   4.80      31.5  2018
6075           Ray-ray McCloud  WR  69  190   4.53      34.5  2018
6084            Anthony Miller  WR  71  201    NaN       NaN  2018
6086           Steven Mitchell  WR  70  189   4.56      32.5  2018
6087             D.J. Moore-02  WR  72  210   4.42      39.5  2018
6088                Jmon Moore  WR  75  207   4.60      38.0  2018
6111              Cam Phillips  WR  72  201    NaN       NaN  2018
6117             Byron Pringle  WR  73  203   4.46      33.5  2018
6120                Trey Quinn  WR  71  203   4.55      33.5  2018
6128             Calvin Ridley  WR  72  189   4.43      31.0  2018
6130           Korey Robertson  WR  73  212   4.56      34.0  2018
6141              Jaleel Scott  WR  77  218   4.56      34.5  2018
6152             Trequan Smith  WR  74  203   4.49      37.5  2018
6161          Courtland Sutton  WR  75  218   4.54      35.5  2018
6163                Auden Tate  WR  77  228   4.68      31.0  2018
6179  Marquez Valdes-Scantling  WR  76  206   4.37      30.5  2018
6190          James Washington  WR  71  213   4.54      34.5  2018
6192               Jester Weah  WR  74  211   4.43      38.0  2018
6197              Karaun White  WR  73  206   4.52      33.5  2018
6202              Jake Wieneke  WR  76  221   4.67      34.0  2018
6206         Cedrick Wilson-02  WR  74  197   4.55      37.0  2018
6209                Javon Wims  WR  75  215   4.53      33.5  2018

[857 rows x 7 columns]

In [12]:
sorted_forty_wr = sorted_wr_col.sort_values("Forty", ascending=True)
print(sorted_forty_wr[WR])

                    Player Pos  Ht   Wt  Forty  Vertical  Year
5805             John Ross  WR  71  188   4.22      37.0  2017
914      Donte' Stallworth  WR  72  197   4.22       NaN  2002
4575            Dri Archer  WR  68  173   4.26      38.0  2014
4332      Marquise Goodwin  WR  69  183   4.27       NaN  2013
5122           J.J. Nelson  WR  70  156   4.28      36.0  2015
3353           Jacoby Ford  WR  69  186   4.28      33.5  2010
1811         Jerome Mathis  WR  71  181   4.28      35.5  2005
3056   Darrius Heyward-Bey  WR  74  210   4.30      38.5  2009
3222           Mike Thomas  WR  68  195   4.30      40.5  2009
2367          Yamon Figurs  WR  71  174   4.30       NaN  2007
2970           Deon Butler  WR  70  182   4.31      34.5  2009
3227      Tiquan Underwood  WR  73  184   4.31      41.5  2009
529           Santana Moss  WR  70  184   4.31       NaN  2001
5811         Curtis Samuel  WR  71  196   4.31      37.0  2017
3931       Travis Benjamin  WR  70  172   4.31      38.0  2012
3679           Clyde Gates  WR  72  192   4.31      40.0  2011
821          Aaron Lockett  WR  67  155   4.31      35.0  2002
5329           Will Fuller  WR  72  186   4.32      33.5  2016
3151          Louis Murphy  WR  74  203   4.32       NaN  2009
690             Tim Carter  WR  72  190   4.32      39.0  2002
1941       Troy Williamson  WR  73  203   4.32       NaN  2005
2403            Jason Hill  WR  72  204   4.32      37.0  2007
2073          Chad Jackson  WR  73  213   4.32      38.5  2006
3237          Mike Wallace  WR  72  199   4.33      40.0  2009
4627         Brandin Cooks  WR  70  189   4.33      36.0  2014
4989       Phillip Dorsett  WR  70  185   4.33      37.0  2015
1374        Carlos Francis  WR  69  198   4.33      38.5  2004
2757        Dexter Jackson  WR  69  182   4.33      29.5  2008
376         Chris Chambers  WR  72  210   4.33      45.0  2001
4249          Tavon Austin  WR  68  174   4.34      32.0  2013
...                    ...  ..  ..  ...    ...       ...   ...
4439              T.J. Moe  WR  71  204   4.74      36.0  2013
2634        Adarius Bowman  WR  75  223   4.74       NaN  2008
70           Chris Daniels  WR  75  217   4.74      33.0  2000
5763           Drew Morgan  WR  72  190   4.74      30.0  2017
228          Cory Peterson  WR  74  195   4.75      32.5  2000
504           David Martin  WR  76  242   4.76       NaN  2001
1469          James Newson  WR  73  213   4.76      31.5  2004
1482          Carlos Perez  WR  71  203   4.78      38.0  2004
1534        Jonathan Smith  WR  70  194   4.78      32.5  2004
1727     Charles Frederick  WR  71  194   4.78      33.0  2005
1588        Ernest Wilford  WR  76  226   4.79      40.5  2004
552             Nate Poole  WR  73  198   4.79      32.5  2001
6072        Tavares Martin  WR  73  177   4.80      31.5  2018
205     Wendell Montgomery  WR  75  203   4.81      35.5  2000
5548      De'Runnya Wilson  WR  77  224   4.85      28.0  2016
5134      Breshad Perriman  WR  74  212    NaN       NaN  2015
5584            Noah Brown  WR  74  222    NaN       NaN  2017
5621           Corey Davis  WR  75  209    NaN       NaN  2017
5709         Greg Ward Jr.  WR  71  186    NaN       NaN  2017
5771           Speedy Noil  WR  71  199    NaN      43.5  2017
5804        Darreus Rogers  WR  73  216    NaN      26.5  2017
5864        Dede Westbrook  WR  72  178    NaN       NaN  2017
5871      Mike Williams-04  WR  76  218    NaN      32.5  2017
5882         Dante Pettis   WR  72  186    NaN       NaN  2018
5910       Braxton Berrios  WR  69  184    NaN       NaN  2018
5921       Deontay Burnett  WR  72  186    NaN       NaN  2018
5999      Daesean Hamilton  WR  73  203    NaN      34.5  2018
6024  Darren Carrington II  WR  74  199    NaN      36.0  2018
6084        Anthony Miller  WR  71  201    NaN       NaN  2018
6111          Cam Phillips  WR  72  201    NaN       NaN  2018

[857 rows x 7 columns]

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.