In [2]:
# Import needed dependencies 
import matplotlib.pyplot as plt 
import pandas as pd 
import scipy.stats as st 
import numpy as np 
from pprint import pprint 

#Set CSV Locations for each NFL Data Set in variable
combine_2000 = "Resources/combine_data.csv"
nfl_stats = "Resources/nfl_stats/Basic_Stats.csv"

# Use pandas csv reader to review data
combine_2000 = pd.read_csv(combine_2000)
nfl_stats = pd.read_csv(nfl_stats)

In [4]:
#view first 10 lines of combine_2000 data. Analyze data set to set goals for clean up
combine_2000.head(10)

,Player,Pos,Ht,Wt,Forty,Vertical,BenchReps,BroadJump,Cone,Shuttle,Year,Pfr_ID,AV,Team,Round,Pick
0,John Abraham,OLB,76,252,4.55,NaN,NaN,NaN,NaN,NaN,2000,AbraJo00,26.0,New York Jets,1.0,13.0
1,Shaun Alexander,RB,72,218,4.58,NaN,NaN,NaN,NaN,NaN,2000,AlexSh00,26.0,Seattle Seahawks,1.0,19.0
2,Darnell Alford,OT,76,334,5.56,25.0,23.0,94.0,8.48,4.98,2000,AlfoDa20,0.0,Kansas City Chiefs,6.0,188.0
3,Kyle Allamon,TE,74,253,4.97,29.0,NaN,104.0,7.29,4.49,2000,NaN,0.0,NaN,NaN,NaN
4,Rashard Anderson,CB,74,206,4.55,34.0,NaN,123.0,7.18,4.15,2000,AndeRa21,6.0,Carolina Panthers,1.0,23.0
5,Jake Arians,K,70,202,NaN,NaN,NaN,NaN,NaN,NaN,2000,arianjak01,0.0,NaN,NaN,NaN
6,LaVar Arrington,OLB,75,250,4.53,NaN,NaN,NaN,NaN,NaN,2000,ArriLa00,31.0,Washington Redskins,1.0,2.0
7,Corey Atkins,OLB,72,237,4.72,31.0,21.0,112.0,7.96,4.39,2000,AtkiCo20,1.0,NaN,NaN,NaN
8,Kyle Atteberry,K,72,167,NaN,NaN,NaN,NaN,NaN,NaN,2000,NaN,0.0,NaN,NaN,NaN
9,Reggie Austin,CB,69,175,4.44,35.0,17.0,119.0,7.03,4.14,2000,AustRe20,3.0,Chicago Bears,4.0,125.0

In [5]:
#view first 10 lines of nfl_stats data. Analyze data set to set goals for clean up
nfl_stats.head(20)

,Age,Birth Place,Birthday,College,Current Status,Current Team,Experience,Height (inches),High School,High School Location,Name,Number,Player Id,Position,Weight (lbs),Years Played
0,NaN,"Grand Rapids , MI",5/23/1921,Notre Dame,Retired,NaN,3 Seasons,71.0,NaN,NaN,"Evans, Fred",NaN,fredevans/2513736,NaN,185.0,1946 - 1948
1,NaN,"Dayton , OH",12/21/1930,Dayton,Retired,NaN,1 Season,70.0,NaN,NaN,"Raiff, Jim",NaN,jimraiff/2523700,NaN,235.0,1954 - 1954
2,56.0,"Temple , TX",9/11/1960,Louisiana Tech,Retired,NaN,1 Season,74.0,NaN,NaN,"Fowler, Bobby",NaN,bobbyfowler/2514295,NaN,230.0,1985 - 1985
3,30.0,"New Orleans , LA",9/30/1986,LSU,Retired,NaN,5 Seasons,73.0,NaN,NaN,"Johnson, Quinn",NaN,quinnjohnson/79593,NaN,255.0,2009 - 2013
4,25.0,"Detroit , MI",3/31/1992,Central Michigan,Active,Pittsburgh Steelers,3rd season,77.0,Clintondale HS,"Clinton Twp.,Macomb Co., MI","Walton, L.T.",96.0,l.t.walton/2552444,DE,305.0,NaN
5,NaN,"Sumner , IL",9/11/1892,Illinois,Retired,NaN,1 Season,73.0,NaN,NaN,"Petty, Ross",NaN,rosspetty/2523136,NaN,180.0,1920 - 1920
6,NaN,"Casper , WY",9/16/1920,Wisconsin,Retired,NaN,3 Seasons,73.0,NaN,NaN,"Farris, Tom",NaN,tomfarris/2513861,NaN,185.0,1946 - 1948
7,22.0,"Navarre , FL",1/31/1995,Clemson,Active,New York Jets,Rookie,77.0,Navarre HS,FL,"Leggett, Jordan",NaN,jordanleggett/2557885,TE,250.0,NaN
8,NaN,NaN,NaN,No College,Retired,NaN,1 Season,NaN,NaN,NaN,"Thompson, Pinky",NaN,pinkythompson/2527303,NaN,NaN,1927 - 1927
9,98.0,"Alverton , PA",2/23/1919,Duquesne,Retired,NaN,1 Season,70.0,NaN,NaN,"Gonda, George",NaN,georgegonda/2515030,NaN,175.0,1942 - 1942
10,NaN,"Orlando , FL",3/8/1945,Tennessee Tech,Retired,NaN,3 Seasons,76.0,NaN,NaN,"Tanner, John",NaN,johntanner/2527011,NaN,231.0,1971 - 1974
11,56.0,"Alton , IL",2/10/1961,Southern University,Retired,NaN,1 Season,69.0,NaN,NaN,"Raglin, Floyd",NaN,floydraglin/2523695,NaN,180.0,1987 - 1987
12,33.0,NaN,12/4/1983,Boise State,Retired,NaN,1 Season,74.0,NaN,NaN,"Zabransky, Jared",NaN,jaredzabransky/2495791,NaN,219.0,2007 - 2007
13,27.0,"Little Rock , AR",11/22/1989,Arkansas,Retired,NaN,3 Seasons,71.0,NaN,NaN,"Adams, Joe",NaN,joeadams/2532782,NaN,185.0,2012 - 2014
14,73.0,"St. Louis , MO",12/8/1943,Missouri,Retired,NaN,8 Seasons,73.0,NaN,NaN,"Otto, Gus",NaN,gusotto/2522592,NaN,220.0,1965 - 1972
15,74.0,"Barberton , OH",9/1/1942,Florida A&M,Retired,NaN,3 Seasons,73.0,NaN,NaN,"Thomas, Gene",NaN,genethomas/2527241,NaN,210.0,1966 - 1968
16,66.0,"Indianola , IA",12/1/1950,Arizona,Retired,NaN,2 Seasons,74.0,NaN,NaN,"Demory, Bill",NaN,billdemory/2512778,NaN,195.0,1973 - 1974
17,25.0,NaN,3/11/1992,Pittsburgh,Active,Washington Redskins,1st season,74.0,NaN,NaN,"Garner, Manasseh",NaN,manassehgarner/2553801,TE,220.0,NaN
18,53.0,"New Orleans , LA",6/14/1963,Louisiana-Lafayette,Retired,NaN,9 Seasons,68.0,NaN,NaN,"Verdin, Clarence",NaN,clarenceverdin/2503464,NaN,160.0,1986 - 1994
19,50.0,"Scranton , PA",1/15/1967,Syracuse,Retired,NaN,1 Season,74.0,NaN,NaN,"DeRiggi, Fred",NaN,fredderiggi/2512828,NaN,268.0,1990 - 1990