In [2]:
# Import needed dependencies 
import matplotlib.pyplot as plt 
import pandas as pd 
import scipy.stats as st 
import numpy as np 
from pprint import pprint 

#Set CSV Locations for each NFL Data Set in variable
combine_2000 = "Resources/combine_data.csv"
nfl_stats = "Resources/nfl_stats/Basic_Stats.csv"

# Use pandas csv reader to review data
combine_2000 = pd.read_csv(combine_2000)
nfl_stats = pd.read_csv(nfl_stats)

In [7]:
combine_2000.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6218 entries, 0 to 6217
Data columns (total 16 columns):
Player       6218 non-null object
Pos          6218 non-null object
Ht           6218 non-null int64
Wt           6218 non-null int64
Forty        6046 non-null float64
Vertical     4796 non-null float64
BenchReps    4212 non-null float64
BroadJump    4754 non-null float64
Cone         3993 non-null float64
Shuttle      4063 non-null float64
Year         6218 non-null int64
Pfr_ID       4895 non-null object
AV           6218 non-null float64
Team         3738 non-null object
Round        3738 non-null float64
Pick         3738 non-null float64
dtypes: float64(9), int64(3), object(4)
memory usage: 777.3+ KB

In [11]:
#view first 10 lines of combine_2000 data. Analyze data set to set goals for clean up
combine_2000.head(20)

,Player,Pos,Ht,Wt,Forty,Vertical,BenchReps,BroadJump,Cone,Shuttle,Year,Pfr_ID,AV,Team,Round,Pick
0,John Abraham,OLB,76,252,4.55,NaN,NaN,NaN,NaN,NaN,2000,AbraJo00,26.0,New York Jets,1.0,13.0
1,Shaun Alexander,RB,72,218,4.58,NaN,NaN,NaN,NaN,NaN,2000,AlexSh00,26.0,Seattle Seahawks,1.0,19.0
2,Darnell Alford,OT,76,334,5.56,25.0,23.0,94.0,8.48,4.98,2000,AlfoDa20,0.0,Kansas City Chiefs,6.0,188.0
3,Kyle Allamon,TE,74,253,4.97,29.0,NaN,104.0,7.29,4.49,2000,NaN,0.0,NaN,NaN,NaN
4,Rashard Anderson,CB,74,206,4.55,34.0,NaN,123.0,7.18,4.15,2000,AndeRa21,6.0,Carolina Panthers,1.0,23.0
5,Jake Arians,K,70,202,NaN,NaN,NaN,NaN,NaN,NaN,2000,arianjak01,0.0,NaN,NaN,NaN
6,LaVar Arrington,OLB,75,250,4.53,NaN,NaN,NaN,NaN,NaN,2000,ArriLa00,31.0,Washington Redskins,1.0,2.0
7,Corey Atkins,OLB,72,237,4.72,31.0,21.0,112.0,7.96,4.39,2000,AtkiCo20,1.0,NaN,NaN,NaN
8,Kyle Atteberry,K,72,167,NaN,NaN,NaN,NaN,NaN,NaN,2000,NaN,0.0,NaN,NaN,NaN
9,Reggie Austin,CB,69,175,4.44,35.0,17.0,119.0,7.03,4.14,2000,AustRe20,3.0,Chicago Bears,4.0,125.0
10,John Baker,P,75,227,NaN,NaN,NaN,NaN,NaN,NaN,2000,BakeJo21,4.0,NaN,NaN,NaN
11,Mark Baniewicz,OT,78,312,5.34,28.0,20.0,96.0,7.72,4.73,2000,NaN,0.0,NaN,NaN,NaN
12,Rashidi Barnes,FS,72,208,4.62,35.0,10.0,114.0,6.92,4.32,2000,BarnRa20,1.0,Cleveland Browns,7.0,225.0
13,David Barrett,CB,70,199,4.44,37.5,16.0,116.0,6.81,4.04,2000,BarrDa22,10.0,Arizona Cardinals,4.0,102.0
14,William Bartee,CB,73,192,4.43,38.5,NaN,124.0,6.70,3.99,2000,BartWi20,9.0,Kansas City Chiefs,2.0,54.0
15,Andrew Bayes,P,74,200,NaN,NaN,NaN,NaN,NaN,NaN,2000,NaN,0.0,NaN,NaN,NaN
16,Terrance Beadles,OG,75,312,5.19,NaN,29.0,NaN,NaN,NaN,2000,NaN,0.0,NaN,NaN,NaN
17,Robert Bean,CB,71,178,4.50,34.5,NaN,122.0,6.87,4.20,2000,BeanRo20,5.0,Cincinnati Bengals,5.0,133.0
18,Anthony Becht,TE,78,270,4.78,33.5,NaN,123.0,6.94,4.08,2000,BechAn00,7.0,New York Jets,1.0,27.0
19,Matt Beck,ILB,75,234,4.65,NaN,NaN,NaN,NaN,NaN,2000,NaN,0.0,NaN,NaN,NaN

In [4]:
#view first 10 lines of nfl_stats data. Analyze data set to set goals for clean up
nfl_stats.head(20)

,Age,Birth Place,Birthday,College,Current Status,Current Team,Experience,Height (inches),High School,High School Location,Name,Number,Player Id,Position,Weight (lbs),Years Played
0,NaN,"Grand Rapids , MI",5/23/1921,Notre Dame,Retired,NaN,3 Seasons,71.0,NaN,NaN,"Evans, Fred",NaN,fredevans/2513736,NaN,185.0,1946 - 1948
1,NaN,"Dayton , OH",12/21/1930,Dayton,Retired,NaN,1 Season,70.0,NaN,NaN,"Raiff, Jim",NaN,jimraiff/2523700,NaN,235.0,1954 - 1954
2,56.0,"Temple , TX",9/11/1960,Louisiana Tech,Retired,NaN,1 Season,74.0,NaN,NaN,"Fowler, Bobby",NaN,bobbyfowler/2514295,NaN,230.0,1985 - 1985
3,30.0,"New Orleans , LA",9/30/1986,LSU,Retired,NaN,5 Seasons,73.0,NaN,NaN,"Johnson, Quinn",NaN,quinnjohnson/79593,NaN,255.0,2009 - 2013
4,25.0,"Detroit , MI",3/31/1992,Central Michigan,Active,Pittsburgh Steelers,3rd season,77.0,Clintondale HS,"Clinton Twp.,Macomb Co., MI","Walton, L.T.",96.0,l.t.walton/2552444,DE,305.0,NaN
5,NaN,"Sumner , IL",9/11/1892,Illinois,Retired,NaN,1 Season,73.0,NaN,NaN,"Petty, Ross",NaN,rosspetty/2523136,NaN,180.0,1920 - 1920
6,NaN,"Casper , WY",9/16/1920,Wisconsin,Retired,NaN,3 Seasons,73.0,NaN,NaN,"Farris, Tom",NaN,tomfarris/2513861,NaN,185.0,1946 - 1948
7,22.0,"Navarre , FL",1/31/1995,Clemson,Active,New York Jets,Rookie,77.0,Navarre HS,FL,"Leggett, Jordan",NaN,jordanleggett/2557885,TE,250.0,NaN
8,NaN,NaN,NaN,No College,Retired,NaN,1 Season,NaN,NaN,NaN,"Thompson, Pinky",NaN,pinkythompson/2527303,NaN,NaN,1927 - 1927
9,98.0,"Alverton , PA",2/23/1919,Duquesne,Retired,NaN,1 Season,70.0,NaN,NaN,"Gonda, George",NaN,georgegonda/2515030,NaN,175.0,1942 - 1942
10,NaN,"Orlando , FL",3/8/1945,Tennessee Tech,Retired,NaN,3 Seasons,76.0,NaN,NaN,"Tanner, John",NaN,johntanner/2527011,NaN,231.0,1971 - 1974
11,56.0,"Alton , IL",2/10/1961,Southern University,Retired,NaN,1 Season,69.0,NaN,NaN,"Raglin, Floyd",NaN,floydraglin/2523695,NaN,180.0,1987 - 1987
12,33.0,NaN,12/4/1983,Boise State,Retired,NaN,1 Season,74.0,NaN,NaN,"Zabransky, Jared",NaN,jaredzabransky/2495791,NaN,219.0,2007 - 2007
13,27.0,"Little Rock , AR",11/22/1989,Arkansas,Retired,NaN,3 Seasons,71.0,NaN,NaN,"Adams, Joe",NaN,joeadams/2532782,NaN,185.0,2012 - 2014
14,73.0,"St. Louis , MO",12/8/1943,Missouri,Retired,NaN,8 Seasons,73.0,NaN,NaN,"Otto, Gus",NaN,gusotto/2522592,NaN,220.0,1965 - 1972
15,74.0,"Barberton , OH",9/1/1942,Florida A&M,Retired,NaN,3 Seasons,73.0,NaN,NaN,"Thomas, Gene",NaN,genethomas/2527241,NaN,210.0,1966 - 1968
16,66.0,"Indianola , IA",12/1/1950,Arizona,Retired,NaN,2 Seasons,74.0,NaN,NaN,"Demory, Bill",NaN,billdemory/2512778,NaN,195.0,1973 - 1974
17,25.0,NaN,3/11/1992,Pittsburgh,Active,Washington Redskins,1st season,74.0,NaN,NaN,"Garner, Manasseh",NaN,manassehgarner/2553801,TE,220.0,NaN
18,53.0,"New Orleans , LA",6/14/1963,Louisiana-Lafayette,Retired,NaN,9 Seasons,68.0,NaN,NaN,"Verdin, Clarence",NaN,clarenceverdin/2503464,NaN,160.0,1986 - 1994
19,50.0,"Scranton , PA",1/15/1967,Syracuse,Retired,NaN,1 Season,74.0,NaN,NaN,"DeRiggi, Fred",NaN,fredderiggi/2512828,NaN,268.0,1990 - 1990

In [27]:
sorted_wr_col = combine_2000[["Pos","Ht","Wt","Forty","Vertical"]]
print(sorted_wr_col.head(17))

    Pos  Ht   Wt  Forty  Vertical
0   OLB  76  252   4.55       NaN
1    RB  72  218   4.58       NaN
2    OT  76  334   5.56      25.0
3    TE  74  253   4.97      29.0
4    CB  74  206   4.55      34.0
5     K  70  202    NaN       NaN
6   OLB  75  250   4.53       NaN
7   OLB  72  237   4.72      31.0
8     K  72  167    NaN       NaN
9    CB  69  175   4.44      35.0
10    P  75  227    NaN       NaN
11   OT  78  312   5.34      28.0
12   FS  72  208   4.62      35.0
13   CB  70  199   4.44      37.5
14   CB  73  192   4.43      38.5
15    P  74  200    NaN       NaN
16   OG  75  312   5.19       NaN

In [29]:
WR = combine_2000[sorted_wr_col["Pos"] == "WR"]
print(WR)

                        Player Pos  Ht   Wt  Forty  Vertical  BenchReps  \
39             Plaxico Burress  WR  77  231   4.59      33.0        NaN
46                 Kwame Cavil  WR  74  208   4.54      39.5        NaN
58                  Chris Cole  WR  72  191   4.37      37.5        NaN
60               Chris Coleman  WR  72  211   4.61      32.5        NaN
61            Laveranues Coles  WR  71  192   4.41      34.0        NaN
70               Chris Daniels  WR  75  217   4.74      33.0        NaN
71             Brandon Daniels  WR  70  211   4.54       NaN        NaN
75               JaJuan Dawson  WR  73  199   4.55      34.0        NaN
81                  Ron Dugans  WR  73  206   4.58       NaN        NaN
88                 Matt Farmer  WR  72  190   4.51      33.0        NaN
89                Danny Farmer  WR  75  217   4.58       NaN        NaN
91               Chafie Fields  WR  73  196   4.43       NaN        NaN
95                Larry Foster  WR  70  198   4.55      37.0        NaN
105              Trevor Gaylor  WR  75  199   4.56      37.5        NaN
107             Sherrod Gideon  WR  71  173   4.66       NaN        NaN
121                 Ricky Hall  WR  74  206   4.52       NaN        NaN
126              Joey Hamilton  WR  73  201   4.54      36.0        NaN
132             Windrell Hayes  WR  71  204   4.50       NaN        NaN
135                Leroy Hodge  WR  73  215   4.54      34.5        NaN
143              Trevor Insley  WR  72  192   4.70       NaN        NaN
149            Darrell Jackson  WR  72  197   4.56       NaN        NaN
164               Dwaune Jones  WR  72  191   4.66       NaN        NaN
179              Marcus Knight  WR  73  180   4.72      28.5        NaN
184                Charles Lee  WR  73  202   4.56      35.5        NaN
187              Anthony Lucas  WR  75  194   4.53      35.0        NaN
189                 Alton Lusk  WR  74  182   4.61      36.5        NaN
205         Wendell Montgomery  WR  75  203   4.81      35.5        NaN
206         Scottie Montgomery  WR  72  196   4.57      36.0        NaN
207               Muneer Moore  WR  73  201   4.52      37.5        NaN
211           Sylvester Morris  WR  75  216   4.60      34.5        NaN
...                        ...  ..  ..  ...    ...       ...        ...
5999          Daesean Hamilton  WR  73  203    NaN      34.5        NaN
6009         Quadree Henderson  WR  68  192   4.50      32.5       12.0
6024      Darren Carrington II  WR  74  199    NaN      36.0        NaN
6036              Richie James  WR  70  183   4.48      35.5        6.0
6055            Christian Kirk  WR  70  201   4.47      35.5       20.0
6057                Chris Lacy  WR  75  205   4.51      33.5       11.0
6059             Jordan Lasley  WR  73  203   4.50      34.5        8.0
6061              Allen Lazard  WR  77  227   4.55      38.0       17.0
6072            Tavares Martin  WR  73  177   4.80      31.5        NaN
6075           Ray-ray McCloud  WR  69  190   4.53      34.5       13.0
6084            Anthony Miller  WR  71  201    NaN       NaN       22.0
6086           Steven Mitchell  WR  70  189   4.56      32.5       13.0
6087             D.J. Moore-02  WR  72  210   4.42      39.5       15.0
6088                Jmon Moore  WR  75  207   4.60      38.0       21.0
6111              Cam Phillips  WR  72  201    NaN       NaN        NaN
6117             Byron Pringle  WR  73  203   4.46      33.5       15.0
6120                Trey Quinn  WR  71  203   4.55      33.5       17.0
6128             Calvin Ridley  WR  72  189   4.43      31.0       15.0
6130           Korey Robertson  WR  73  212   4.56      34.0       13.0
6141              Jaleel Scott  WR  77  218   4.56      34.5       16.0
6152             Trequan Smith  WR  74  203   4.49      37.5       12.0
6161          Courtland Sutton  WR  75  218   4.54      35.5       18.0
6163                Auden Tate  WR  77  228   4.68      31.0        NaN
6179  Marquez Valdes-Scantling  WR  76  206   4.37      30.5       15.0
6190          James Washington  WR  71  213   4.54      34.5       14.0
6192               Jester Weah  WR  74  211   4.43      38.0       15.0
6197              Karaun White  WR  73  206   4.52      33.5       24.0
6202              Jake Wieneke  WR  76  221   4.67      34.0        9.0
6206         Cedrick Wilson-02  WR  74  197   4.55      37.0        9.0
6209                Javon Wims  WR  75  215   4.53      33.5        NaN

      BroadJump  Cone  Shuttle  Year    Pfr_ID    AV                 Team  \
39        115.0   NaN      NaN  2000  BurrPl00  25.0  Pittsburgh Steelers
46        118.0   NaN      NaN  2000  CaviKw00   0.0                  NaN
58        125.0  6.76     4.09  2000  ColeCh00   1.0       Denver Broncos
60        110.0  6.79     4.10  2000  ColeCh01   0.0                  NaN
61        115.0  6.89     4.39  2000  ColeLa00  26.0        New York Jets
70        115.0  7.20     4.24  2000       NaN   0.0                  NaN
71          NaN   NaN      NaN  2000       NaN   0.0                  NaN
75        117.0  6.96     4.16  2000  DawsJa00   5.0     Cleveland Browns
81        117.0   NaN      NaN  2000  DugaRo00   6.0   Cincinnati Bengals
88        108.0  6.63     3.94  2000       NaN   0.0                  NaN
89          NaN   NaN      NaN  2000  FarmDa00   5.0  Pittsburgh Steelers
91          NaN   NaN      NaN  2000       NaN   0.0                  NaN
95        121.0  6.88     4.06  2000  FostLa00   5.0                  NaN
105       121.0  7.03     4.29  2000  GaylTr00   7.0   San Diego Chargers
107         NaN   NaN      NaN  2000       NaN   0.0                  NaN
121         NaN   NaN      NaN  2000       NaN   0.0                  NaN
126       116.0  7.57     4.41  2000       NaN   0.0                  NaN
132         NaN  7.33     4.18  2000  HayeWi00   1.0        New York Jets
135       116.0  7.14     4.21  2000       NaN   0.0                  NaN
143         NaN   NaN      NaN  2000  InslTr00   2.0                  NaN
149         NaN   NaN      NaN  2000  JackDa00  24.0     Seattle Seahawks
164         NaN   NaN      NaN  2000       NaN   0.0                  NaN
179       106.0  7.11     4.38  2000  KnigMa00   0.0                  NaN
184       125.0  7.30     4.25  2000  LeexCh00   1.0    Green Bay Packers
187       121.0   NaN      NaN  2000       NaN   0.0                  NaN
189       122.0  7.16     4.26  2000       NaN   0.0                  NaN
205       117.0  7.01     4.24  2000       NaN   0.0                  NaN
206       117.0  7.16     4.11  2000  MontSc00   2.0                  NaN
207       129.0  6.91     4.09  2000       NaN   0.0                  NaN
211       119.0  7.06     4.17  2000  MorrSy00   6.0   Kansas City Chiefs
...         ...   ...      ...   ...       ...   ...                  ...
5999      118.0  6.84     4.15  2018  HamiDa01   0.0                  NaN
6009      120.0  6.89     4.28  2018  HendQu00   0.0                  NaN
6024      120.0   NaN      NaN  2018       NaN   0.0                  NaN
6036      122.0  6.87     4.16  2018       NaN   0.0                  NaN
6055      115.0  7.09     4.45  2018  KirkCh01   0.0                  NaN
6057      120.0   NaN      NaN  2018       NaN   0.0                  NaN
6059      112.0   NaN     4.19  2018  LaslJo00   0.0                  NaN
6061      122.0   NaN      NaN  2018  LazaAl00   0.0                  NaN
6072        NaN   NaN      NaN  2018       NaN   0.0                  NaN
6075      113.0   NaN      NaN  2018       NaN   0.0                  NaN
6084        NaN   NaN      NaN  2018  MillAn02   0.0                  NaN
6086      121.0  6.75     4.40  2018       NaN   0.0                  NaN
6087      132.0  6.95     4.07  2018  MoorD.00   0.0                  NaN
6088      120.0  6.56     4.04  2018       NaN   0.0                  NaN
6111        NaN   NaN      NaN  2018  PhilCa01   0.0                  NaN
6117      120.0  6.87     4.40  2018  PrinBy00   0.0                  NaN
6120      116.0  6.91     4.19  2018  QuinTr00   0.0                  NaN
6128      110.0  6.88     4.41  2018  RidlCa00   0.0                  NaN
6130      123.0   NaN      NaN  2018  RobeKo00   0.0                  NaN
6141      124.0  7.20     4.40  2018       NaN   0.0                  NaN
6152      130.0  6.97     4.50  2018       NaN   0.0                  NaN
6161      124.0  6.57     4.11  2018  SuttCo00   0.0                  NaN
6163      112.0   NaN      NaN  2018  TateAu00   0.0                  NaN
6179      124.0   NaN      NaN  2018       NaN   0.0                  NaN
6190      120.0  7.11     4.32  2018  WashJa00   0.0                  NaN
6192      129.0  7.24     4.41  2018  WeahJe00   0.0                  NaN
6197      118.0  7.16     4.57  2018       NaN   0.0                  NaN
6202      114.0  7.24     4.37  2018       NaN   0.0                  NaN
6206      121.0  6.89     4.23  2018  WilsCe01   0.0                  NaN
6209      113.0  7.00      NaN  2018  WimsJa00   0.0                  NaN

      Round   Pick
39      1.0    8.0
46      NaN    NaN
58      3.0   70.0
60      NaN    NaN
61      3.0   78.0
70      NaN    NaN
71      NaN    NaN
75      3.0   79.0
81      3.0   66.0
88      NaN    NaN
89      4.0  103.0
91      NaN    NaN
95      NaN    NaN
105     4.0  111.0
107     NaN    NaN
121     NaN    NaN
126     NaN    NaN
132     5.0  143.0
135     NaN    NaN
143     NaN    NaN
149     3.0   80.0
164     NaN    NaN
179     NaN    NaN
184     7.0  242.0
187     NaN    NaN
189     NaN    NaN
205     NaN    NaN
206     NaN    NaN
207     NaN    NaN
211     1.0   21.0
...     ...    ...
5999    NaN    NaN
6009    NaN    NaN
6024    NaN    NaN
6036    NaN    NaN
6055    NaN    NaN
6057    NaN    NaN
6059    NaN    NaN
6061    NaN    NaN
6072    NaN    NaN
6075    NaN    NaN
6084    NaN    NaN
6086    NaN    NaN
6087    NaN    NaN
6088    NaN    NaN
6111    NaN    NaN
6117    NaN    NaN
6120    NaN    NaN
6128    NaN    NaN
6130    NaN    NaN
6141    NaN    NaN
6152    NaN    NaN
6161    NaN    NaN
6163    NaN    NaN
6179    NaN    NaN
6190    NaN    NaN
6192    NaN    NaN
6197    NaN    NaN
6202    NaN    NaN
6206    NaN    NaN
6209    NaN    NaN

[857 rows x 16 columns]